[profile.default]
src = "contracts"
test = "test"
out = "out"
libs = ["lib"]

remappings = [
  "@openzeppelin/contracts-upgradeable/=node_modules/@openzeppelin/contracts-upgradeable/",
  "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/",
  "forge-std/=lib/forge-std/src/"
]
